name: oci-deploy
on:
  push:
    branches:
      - '*'
jobs:
  build-and-push:
    name: Build and push image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: build and push to docker
      - uses: docker/build-push-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: ${{ github.repository }}
          tag_with_ref: true
          tag_with_sha: true
          tags: ${{ github.sha }}

      - name: 'Wait for SSH'
        run: |
          while ! nc -w5 -z ${{ secrets.OCI_IP_TERCERA }} 22; do
                  sleep 5
                  echo "SSH not available..."
          done; echo "SSH ready!"
        -name: Build the Docker image
        -uses: actions/checkout@v2
         run: docker build . --file Dockerfile --tag manager:$(date +%s)
