name: oci-deploy
on:
  push:
    branches:
      - '*'
jobs:
  build-job:
    name: Build Job
    runs-on: ubuntu-latest
    steps:
      - name: 'Start build job'
        run: |
          echo "Starting the build job."
      - name: 'Checkout'
        uses: actions/checkout@v2

      - name: 'Setup Java'
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: 'Check Java Version'
        run: |
          java --version

      - name: 'Wait for SSH'
        run: |
          while ! nc -w5 -z ${{ secrets.OCI_IP_TERCERA }} 22; do
                  sleep 5
                  echo "SSH not available..."
          done; echo "SSH ready!"
