name: cicd-demo
on:
  push:
    branches:
      - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 'Setup Java'
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: 'Checkout'
        uses: actions/checkout@v2

      - name: Build with maven
        run: |
          mvn install

      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: yparada/MANAGER
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          snapshot: true
      - name: 'Wait for SSH'
        run: |
          while ! nc -w5 -z ${{ env.INSTANCE_IP }} 22; do
                  sleep 5
                  echo "SSH not available..."
          done; echo "SSH ready!"

      - name: 'Stop App'
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.OCI_IP_TERCERA }}
          username: opc
          key: ${{ secrets.VM_SSH_PRIVATE_KEY_TERCERA }}
          script: |
            sudo docker run -dp 8080:8080  yparada/manager:latest
